version: "3.3"
services:
  db:
    image: mysql:5.7
    container_name: AutotechDB
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - /var/lib/mysql
      - ./dump:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: urubu100
      MYSQL_DATABASE: AutotechDB
      MYSQL_USER: AutotechDB
      MYSQL_PASSWORD: urubu100
      MYSQL_ROOT_HOST: "%"
    networks:
      app_net:
        ipv4_address: 172.20.0.2
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
